cabal-version: 3.14
name: maple
version: 0.1.0.0
synopsis: Red-green trees lossless syntax trees (CSTs) library
description:
  Maple is a Haskell library for lossless syntax trees (CSTs). Specifically, we work with data structures called red-green trees also used by roslyn and rust-analyzer.

license: Apache-2.0
license-file: LICENSE
author: Gabriel
maintainer: gabriel@minatel.dev
category: Language
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

library
  import: warnings
  exposed-modules:
    Maple
    Maple.Ast
    Maple.Builder
    Maple.Cache
    Maple.Green
    Maple.Position
    Maple.Red

  build-depends:
    base ^>=4.20.2.0,
    hashable ^>=1.5.1.0,
    mtl ^>=2.3.1,
    symbolize ^>=1.0.3,
    text ^>=2.1,
    unordered-containers >=0.2.21,
    vector ^>=0.13.1

  hs-source-dirs: src
  default-language: GHC2024

test-suite maple-test
  import: warnings
  default-language: GHC2024
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    base ^>=4.20.2.0,
    hspec ^>=2.11,
    maple,
    symbolize,
    text,
    unordered-containers,
    vector
